import os
import json
from fpdf import FPDF
from datetime import datetime

REPORTS_DIR = os.path.join(os.path.dirname(__file__), "reports")
os.makedirs(REPORTS_DIR, exist_ok=True)

class ReportPDF(FPDF):
    def header(self):
        self.set_fill_color(30, 30, 60)
        self.rect(0, 0, 210, 30, 'F')
        self.set_font("Helvetica", "B", 18)
        self.set_text_color(255, 255, 255)
        self.set_y(8)
        self.cell(0, 14, "AI Placement Assessment Report", align="C")
        self.set_text_color(0, 0, 0)
        self.ln(22)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, f"Generated by AI Mock Exam Platform  |  Page {self.page_no()}", align="C")

def generate_scorecard_pdf(scorecard: dict) -> str:
    pdf = ReportPDF()
    pdf.add_page()

    session_id = scorecard.get("session_id", "unknown")
    pdf_path = os.path.join(REPORTS_DIR, f"report_{session_id}.pdf")

    pdf.set_fill_color(240, 240, 255)
    pdf.rect(10, pdf.get_y(), 190, 50, 'F')
    pdf.set_font("Helvetica", "B", 14)
    pdf.set_text_color(30, 30, 100)
    pdf.cell(0, 10, f"Candidate: {scorecard.get('name', 'Anonymous')}", ln=True, x=15)

    pdf.set_font("Helvetica", "", 12)
    pdf.set_text_color(50, 50, 50)
    pdf.cell(0, 8, f"Category: {scorecard.get('category', 'N/A')}", ln=True, x=15)
    pdf.cell(0, 8, f"Date: {scorecard.get('created_at', datetime.now().isoformat())[:10]}", ln=True, x=15)

    score = scorecard.get("score", 0)
    total = scorecard.get("total", 0)
    pct = scorecard.get("percentage", 0)
    pdf.ln(2)

    pdf.set_font("Helvetica", "B", 32)
    color = (46, 160, 67) if pct >= 70 else (220, 100, 0) if pct >= 40 else (200, 30, 30)
    pdf.set_text_color(*color)
    pdf.cell(0, 18, f"{score} / {total}  ({pct}%)", align="C", ln=True)

    band = "Excellent" if pct >= 85 else "Good" if pct >= 70 else "Average" if pct >= 50 else "Needs Improvement"
    pdf.set_font("Helvetica", "I", 13)
    pdf.set_text_color(80, 80, 80)
    pdf.cell(0, 8, f"Performance Band: {band}", align="C", ln=True)
    pdf.ln(6)

    recs = scorecard.get("recommendations", [])
    if isinstance(recs, str):
        try:
            recs = json.loads(recs)
        except:
            recs = []

    if recs:
        pdf.set_font("Helvetica", "B", 13)
        pdf.set_text_color(30, 30, 100)
        pdf.cell(0, 10, "Personalized Study Recommendations", ln=True)
        pdf.set_draw_color(200, 200, 220)
        pdf.line(10, pdf.get_y(), 200, pdf.get_y())
        pdf.ln(3)

        for i, rec in enumerate(recs, 1):
            pdf.set_fill_color(250, 250, 255)
            pdf.set_font("Helvetica", "B", 11)
            pdf.set_text_color(60, 60, 140)
            pdf.cell(0, 8, f"{i}. {rec.get('topic', '')}", ln=True, fill=True)
            pdf.set_font("Helvetica", "", 10)
            pdf.set_text_color(70, 70, 70)
            pdf.multi_cell(0, 6, f"   Priority: {rec.get('priority','Medium')}  |  Why: {rec.get('reason','Strengthen this area')}")
            pdf.ln(2)

    pdf.output(pdf_path)
    return pdf_path


def generate_ats_pdf(ats_result: dict) -> str:
    pdf = ReportPDF()
    pdf.add_page()

    session_id = ats_result.get("session_id", "ats_unknown")
    pdf_path = os.path.join(REPORTS_DIR, f"ats_{session_id}.pdf")

    score = ats_result.get("ats_score", 0)
    color = (46, 160, 67) if score >= 75 else (220, 100, 0) if score >= 50 else (200, 30, 30)

    pdf.set_font("Helvetica", "B", 14)
    pdf.set_text_color(30, 30, 100)
    pdf.cell(0, 10, "ATS Resume Analysis Report", ln=True)
    pdf.ln(3)
    pdf.set_font("Helvetica", "B", 36)
    pdf.set_text_color(*color)
    pdf.cell(0, 18, f"ATS Score: {score}%", align="C", ln=True)

    band = "Strong" if score >= 75 else "Moderate" if score >= 50 else "Weak"
    pdf.set_font("Helvetica", "I", 13)
    pdf.set_text_color(80, 80, 80)
    pdf.cell(0, 8, f"Resume Band: {band}", align="C", ln=True)
    pdf.ln(6)

    feedback = ats_result.get("feedback", "")
    if feedback:
        pdf.set_font("Helvetica", "B", 13)
        pdf.set_text_color(30, 30, 100)
        pdf.cell(0, 10, "AI Feedback", ln=True)
        pdf.set_font("Helvetica", "", 11)
        pdf.set_text_color(50, 50, 50)
        pdf.multi_cell(0, 7, feedback)

    pdf.output(pdf_path)
    return pdf_path
